# Generated by Django 3.0.4 on 2020-04-05 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('data', models.DateField(auto_now=True)),
                ('meta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recebido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descricao', models.TextField()),
                ('fins', models.TextField()),
                ('info', models.TextField()),
                ('foto', models.ImageField(upload_to='media2')),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'causa',
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(auto_now=True)),
                ('horario', models.TimeField(auto_now=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Causa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doacao',
            },
        ),
    ]
