# Generated by Django 3.0.4 on 2020-04-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200409_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='codigo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
