# Generated by Django 3.0.4 on 2020-04-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='codigo',
        ),
    ]
