# Generated by Django 3.0.4 on 2020-04-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_userprofile_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='causa',
            name='city',
            field=models.CharField(default='cidade', max_length=100),
        ),
        migrations.AddField(
            model_name='causa',
            name='email',
            field=models.CharField(default='email', max_length=70),
        ),
        migrations.AddField(
            model_name='causa',
            name='fone',
            field=models.CharField(default='fone', max_length=20),
        ),
        migrations.AddField(
            model_name='causa',
            name='ong',
            field=models.CharField(default='ong', max_length=60),
        ),
        migrations.AddField(
            model_name='causa',
            name='uf',
            field=models.CharField(default='uf', max_length=2),
        ),
    ]
