# Generated by Django 3.0.4 on 2020-04-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200423_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causa',
            name='city',
        ),
        migrations.RemoveField(
            model_name='causa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='causa',
            name='fone',
        ),
        migrations.RemoveField(
            model_name='causa',
            name='ong',
        ),
        migrations.RemoveField(
            model_name='causa',
            name='uf',
        ),
    ]
