# Generated by Django 3.2 on 2021-07-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200423_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
