# Generated by Django 3.2.3 on 2021-07-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sugestao'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugestao',
            name='donatario',
            field=models.CharField(default=20, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sugestao',
            name='meta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
