# Generated by Django 3.2.3 on 2021-07-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210704_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugestao',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
