# Generated by Django 3.2.3 on 2021-07-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sugestao_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sugestao',
            table='Sugestao',
        ),
    ]
