# Generated by Django 3.2.3 on 2021-07-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_sugestao_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sugestao',
            table='sugestao',
        ),
    ]
