# Generated by Django 3.2.3 on 2021-07-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_sugestao_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugestao',
            name='status',
            field=models.BooleanField(),
        ),
    ]
