# Generated by Django 3.2.3 on 2021-07-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_sugestao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugestao',
            name='status',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
    ]
