# Generated by Django 3.2.3 on 2021-07-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_sugestao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugestao',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
