# Generated by Django 3.2.3 on 2021-07-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_sugestao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='pago',
            field=models.SmallIntegerField(default=0),
        ),
    ]
