# Generated by Django 3.2.3 on 2021-07-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_doacao_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='causa',
            name='horario',
            field=models.TimeField(auto_now=True),
        ),
    ]
